라운지 초대 링크 모달 UI
mju-likelion/lionqueen pull request #111
Opened 2022-07-23 15:36 UTC by qkrthdus605

라운지 생성 이후 모달에 초대 링크를 띄우는 UI

2022-07-24 06:39 UTC, syeon2565 reviewed
완성 ui화면 캡쳐해서 올려주면 좋을 것 같습니다.

2022-07-24 06:39 UTC, syeon2565 commented on src/components/LoungeSelect/InviteModal.tsx
> +  justify-content: column;
justify-content에 column이 있나요..? 축을 정의하는 css속성은 flex-direction입니다. 
display: flex와 같이 쓰입니다.
모달 자체에서 children에 들어갈 내용들이 스타일이 되어있습니다. [참고](https://github.com/mju-likelion/lionqueen/blob/develop/src/DesignSystem/Modal/styles.tsx) (23~25번째의 스타일 속성)
display속성도 필요한 코드가 아닌 것으로 보입니다. 확인 부탁드려요.

2022-07-24 14:07 UTC, ndaemy commented on src/components/LoungeSelect/InviteModal.tsx
> +  justify-content: column;
:bbadda:

2022-07-25 15:46 UTC, ndaemy requested changes

2022-07-25 15:46 UTC, ndaemy commented on src/components/LoungeSelect/InviteModal.tsx
> +    'https://liontown.city/lounge/123?inviteCode=123123?123?inviteCode=123123?',
이거 env 로 관리해주세요!

2022-07-25 15:47 UTC, ypyp66 commented on src/components/LoungeSelect/InviteModal.tsx
> +    'https://liontown.city/lounge/123?inviteCode=123123?123?inviteCode=123123?',
이거 url복사하면 되는거아닌지?

2022-07-25 15:47 UTC, qkrthdus605 commented on src/components/LoungeSelect/InviteModal.tsx
> +    'https://liontown.city/lounge/123?inviteCode=123123?123?inviteCode=123123?',
초대링크요??

2022-07-25 15:48 UTC, qkrthdus605 commented on src/components/LoungeSelect/InviteModal.tsx
> +    'https://liontown.city/lounge/123?inviteCode=123123?123?inviteCode=123123?',
저거는 임시로만 넣어놓은 아무링크이긴 하다만 state로 관리하면 변수로 받아오니까 상관없는거 아닌가욤.......??......

2022-08-12 05:20 UTC, ndaemy approved these changes

2022-08-12 05:24 UTC, merged