feat: navBar UI
mju-likelion/lionqueen pull request #26
Opened 2022-05-11 07:05 UTC by yuraup

2022-06-24 18:19 UTC, Crmal commented on src/components/NavBar/index.tsx
> +  background-color: rgba(255, 187, 23, 0.7);
이게 뭐죠? 궁금해서요 😃

2022-06-24 18:20 UTC, yuraup commented on src/components/NavBar/index.tsx
> +  background-color: rgba(255, 187, 23, 0.7);
background-color: rgba(255, 187, 23, 0.7);
이렇게 해도 되나요?

2022-06-24 18:20 UTC, yuraup commented on src/components/NavBar/index.tsx
> +  background-color: rgba(255, 187, 23, 0.7);
궁금하면 프론트 스터디 하세요~!

2022-06-25 06:41 UTC, yuraup commented on src/components/NavBar/index.tsx
> +  background-color: rgba(255, 187, 23, 0.7);
opacity 적용하니까 '메뉴'글씨랑 사자 이미지랑 등등 다 투명해져서 이렇게 썼는데 다른 방법으로 해야 할까요?

2022-06-25 08:01 UTC, syeon2565 commented on src/components/NavBar/index.tsx
> +import ImgBox from '../../../public/image/lion.svg';
ImgBox가 무슨 사진인지 코드만 봐서 잘 몰라서, 
이름보면 알 수 있도록 수정해도 좋을 것 같습니다.

2022-06-25 08:01 UTC, syeon2565 commented on src/components/NavBar/index.tsx
> +const ImgContainer = styled(ImgBox)`
이것또한 이미지 컨테이너가 무엇을 뜻하는지..?
그래도 styled(ImgBox) 배운거 바로 응용하는건 :ggoodd: 잘하고 있씁니당 ~ ~

2022-06-25 08:05 UTC, ndaemy requested changes

2022-06-25 08:05 UTC, ndaemy commented on src/components/NavBar/index.tsx
> +  background-color: rgba(255, 187, 23, 0.7);
네 그렇게 하는게 맞아요
opacity는 해당 div에 전체적으로 적용되는 투명도라, 적용할거면 background-color로 적용하는게 맞아요. 
그런데, backgrouond-color에서도 alpha값을 주는 것은 performance issue를 발생 시킬 수 있어서, 굳이 꼭 alpha값이 필요한게 아니라면 static한 rgb값을 구해서 넣는 것을 추천해요.

[관련 stackoverflow](https://stackoverflow.com/questions/38523826/text-css-rendering-performance-rgba-vs-hex-vs-opacity)

2022-06-25 08:05 UTC, ndaemy commented on src/components/NavBar/index.tsx
> +import ImgBox from '../../../public/image/lion.svg';
svg 파일은 코드라서 public폴더에 들어갈 필요가 없다고 생각하는데 (next 에서 public폴더에 넣는 이유는 다운로드가 가능하게 하기 위함이니까) 혹시 public폴더에 넣은 이유가 있나요?

2022-06-25 08:05 UTC, ndaemy commented on src/components/NavBar/index.tsx
> +import ImgBox from '../../../public/image/lion.svg';
그리고 여기 같은 경우는, lion.svg를 가져왔는데 그 이름을 ImgBox라고 달아서 이름만 보고 이게 무슨 파일인지 알기 힘들거같아요. naming을 다시 고민해보시는 것이 좋을 것 같습니다.

2022-06-25 08:05 UTC, ndaemy commented on src/pages/index.tsx
>  import LoadingPage from '../DesignSystem/Loading';
요기 DesignSystem도 ~ alias 적용되어 있지 않나요? 이왕 alias 를 적용했으면 사용해주는게 좋을거같아요.

2022-06-25 08:18 UTC, yuraup commented on src/components/NavBar/index.tsx
> +  background-color: rgba(255, 187, 23, 0.7);
감사합니다!

2022-06-25 13:11 UTC, ndaemy requested changes

2022-06-25 13:11 UTC, ndaemy commented on src/components/NavBar/index.tsx
> +        <ButtonStyle2>로그아웃</ButtonStyle2>
이런 식의 네이밍은 좋지 않아요..
좋은 네이밍과 나쁜 네이밍에 관련된 많은 얘기가 있지만, 가장 안좋은 네이밍이 바로 이렇게 숫자 붙이는 겁니다..
네이밍에 관련된 좋은 글은 [여기](https://velog.io/@joonsikryu/%EA%B0%9C%EB%B0%9C-%EC%8B%9C%EA%B0%84%EC%9D%84-%EC%A4%84%EC%97%AC%EC%A3%BC%EB%8A%94-%EC%9D%B4%EB%A6%84-%EC%A7%93%EA%B8%B0%EC%99%80-%EC%A3%BC%EC%84%9D-%EC%93%B0%EA%B8%B0#%EB%B3%B5%EC%88%98%ED%98%95%EC%9D%84-%EB%82%98%ED%83%80%EB%82%B4%EB%8A%94-s%EB%A5%BC-%EB%B6%99%EC%9D%BC%EA%B9%8C-%EB%A7%90%EA%B9%8C) 보시면 좋을 것 같고, 간단히 요약하자면 (리액트 컴퍼넌트 기준으로) 이름만 보고 뭘 보여주는지 알 수 있는 네이밍이 가장 좋아요. 최소한 2는 안됩니다 ❌

2022-06-25 13:11 UTC, ndaemy commented on src/components/NavBar/index.tsx
> +        <ButtonStyle2>로그아웃</ButtonStyle2>
그리고 Style이 뒤에 붙는 것도 좋지 않아보여요. 저거 자체가 스타일에 대해 반환하는 함수가 아닌 리액트 컴퍼넌트니까요. 추천을 드리자면
```
<PrimaryButton />
<SecondaryButton />
```

혹은

```
<StyledPrimaryButton />
<StyledSecondaryButton />
```

을 추천드립니다

2022-06-25 13:11 UTC, ndaemy commented on src/components/icons/LionLogo.tsx
> +  height?: string;
svg 컴퍼넌트 같은 경우는 number 타입도 받을 수 있고 string 타입도 받을 수 있어요. 근데 이 컴퍼넌트에서는 숫자 형태를 받으니까, 보다 정확한 타입 추론을 위해 number로 해보는건 어떨까요?

2022-06-25 13:11 UTC, ndaemy commented on src/components/icons/LionLogo.tsx
> +  height?: string;
number인 경우에는 123x 같은 걸 보낼 수 없지만, string 이라면 123x 처럼 오타를 낼 수도 있으니까요?

2022-06-27 14:31 UTC, ndaemy approved these changes

2022-07-02 17:22 UTC, ypyp66 approved these changes

2022-07-09 09:09 UTC, Bhanjo approved these changes
지금 테스트 보면 빨간색 X가 있는데 이거는 origin/develop을 머지 해서 해결해주세요

2022-07-09 09:09 UTC, Bhanjo commented on src/components/NavBar/index.tsx
> +  color: #2e2e2e;
globalStlye에 이미 텍스트 기본 색상이 2e2e2e로 돼있어서 이건 없어도 됩니다!

2022-07-09 09:09 UTC, Bhanjo commented on src/components/NavBar/index.tsx
> +import LionLogo from '../icons/LionLogo';
위에 버튼 한 것 처럼 alias(~)로 바꿔주세요!

2022-07-09 09:13 UTC, merged