라운지 목록 UI
mju-likelion/lionqueen pull request #54
Opened 2022-06-19 04:49 UTC by JJongsKim

2022-06-19 12:24 UTC, ypyp66 commented on src/DesignSystem/FloorButton/FloorButton.stories.tsx
> +export const Default = Template.bind({});
정의된 스토리가 하나도 없는데 스토리를 만든 이유가 있을까요?
그리고 해당 컴포넌트는 특정 상황에서만 사용되는 컴포넌트가 아닌가 싶네요

2022-06-19 12:24 UTC, ypyp66 commented on src/DesignSystem/LoungeDoor/LoungeDoor.stories.tsx
> +export const Default = Template.bind({});
정의된 스토리가 하나도 없는데 스토리를 만든 이유가 있을까요?
그리고 해당 컴포넌트는 특정 상황에서만 사용되는 컴포넌트가 아닌가 싶네요 - 2

2022-06-19 12:24 UTC, ypyp66 commented on src/pages/lounge.tsx
> +// const TestDoor = [1, 2, 3, 4];
주석은 제거해주세요

2022-06-19 12:38 UTC, ypyp66 approved these changes

2022-06-19 12:38 UTC, ypyp66 commented on src/DesignSystem/LoungeDoor/index.tsx
> +    </LoungeFloor>
className을 부여하는 것이 아닌, styled 태그 정의 내에서 해결하거나 각 태그로 분리해주세요

2022-06-20 13:12 UTC, JJongsKim commented on src/DesignSystem/LoungeDoor/index.tsx
> +    </LoungeFloor>
넵 반영하겠습니다!

2022-06-24 05:19 UTC, ypyp66 approved these changes

2022-06-24 05:19 UTC, ypyp66 commented on src/pages/lounge/FloorButton.tsx
> +`;
파일 밑 부분으로 내려주세요

2022-06-24 07:32 UTC, ypyp66 commented on src/pages/lounge/index.tsx
> +const TestFloor: string[] = ['10F', '9F', '8F', '7F', '6F', '5F', '4F', '3F', '2F', '1F'];
이건 위로

2022-06-24 07:33 UTC, JJongsKim commented on src/pages/lounge/FloorButton.tsx
> +`;
넵!

2022-06-24 08:05 UTC, ypyp66 commented on src/pages/lounge/LoungeDoor.tsx
> +];
변수 및 타입 선언은 위로
스타일 선언만 밑으로

2022-06-24 08:07 UTC, ypyp66 commented on src/pages/lounge/LoungeDoor.tsx
> +];
```suggestion
type TestDoorType = {
  userNum: number;
  userName: string;
};

const TestDoor: TestDoorType[] = [
  { userNum: 1, userName: '수정' },
  { userNum: 2, userName: '유라' },
  { userNum: 3, userName: '소연' },
  { userNum: 4, userName: '수진' },
];
```

2022-06-24 11:35 UTC, yuraup approved these changes

2022-06-25 13:24 UTC, ndaemy requested changes

2022-06-25 13:24 UTC, ndaemy commented on src/dto/theme.dto.ts
> +export interface customThemeDto {
DTO는 Data Transfer Object 인데, 얘는 interface 니까 이름이 맞지 않는 것 같아요.
DTO라는 네이밍은 정말 data를 transfer하는 object에 붙여야 하는 이름입니다
[참고참고](https://gmlwjd9405.github.io/2018/12/25/difference-dao-dto-entity.html)

2022-06-25 13:24 UTC, ndaemy commented on src/pages/lounge/FloorButton.tsx
> +  background-color: ${theme.colors.primary.yellow};
요거 어떤 분들은 `${({theme}) => theme.colors.primary.yellow}` 로 쓰시고 어떤 분들은 theme을 import 해와서 수정님처럼 쓰는데, 하나로 통일되는게 좋을거같아요.

2022-06-25 13:24 UTC, ndaemy commented on src/pages/lounge/FloorButton.tsx
> +  background-color: ${theme.colors.primary.yellow};
☝️ 의 문법이 먹히는건, global styled-component에서 theme을 주입해주어서 가능한겁니다

2022-06-25 13:24 UTC, ndaemy commented on src/pages/lounge/FloorButton.tsx
> +import { theme } from '../../styles/theme';
요거 ~/ alias 가 있으니까 줄여서 이렇게도 쓸 수 있을거같아요
`import { theme } from '../../styles/theme';`

2022-06-25 13:24 UTC, ndaemy commented on src/pages/lounge/index.tsx
> +import Gear from '../../../public/image/Gear.svg';
[요 코드리뷰](https://github.com/mju-likelion/lionqueen/pull/26#discussion_r906651627)를 참고해보시면 좋을것같습니다

2022-06-25 13:24 UTC, ndaemy commented on src/styles/theme.ts
> +export const theme: customThemeDto = {
이런 경우에는 저 타입(인터페이스)의 이름을 Theme 혹은 ThemeType 정도로만 해주셔도 좋아요. 위의 dto 관련 네이밍 리뷰랑 같은 맥락에서 남기는 리뷰입니다.

2022-06-25 14:42 UTC, ypyp66 commented on src/dto/theme.dto.ts
> +export interface customThemeDto {
나도 DTO가 맞나 했는데 배워갑니다

2022-06-25 16:37 UTC, ypyp66 commented on src/pages/lounge/FloorButton.tsx
> +import { theme } from '../../styles/theme';
`~/styles/theme ` 입니다 ㅋㅋ

2022-06-25 16:38 UTC, ypyp66 reviewed
theme 타입 선언 제가할께여

2022-06-25 16:44 UTC, JJongsKim commented
> theme 타입 선언 제가할께여

넵 !!

2022-06-25 17:04 UTC, syeon2565 commented on src/pages/lounge/FloorButton.tsx
> +import { theme } from '../../styles/theme';
ㅋㅋㅋㅋㅋ 줄여서 쓸 수 있다고했는데 그대로인 마법.. 이걸 밝혀내는 갓연빈..
tsconfig를 봐서 어떤게 어떤걸로 줄여질 수 있는지 보면 좋아요~

2022-06-25 17:15 UTC, ypyp66 commented on src/pages/lounge/index.tsx
> +const FloorNumber: string[] = ['10F', '9F', '8F', '7F', '6F', '5F', '4F', '3F', '2F', '1F'];
이 부분도 따로 상수파일로 분리 및 import 하면 좋을 것 같아요

2022-06-25 17:15 UTC, ypyp66 commented on src/components/lounge/NameBoard.tsx
> +  box-shadow: 0 7px 5px #7f7f7f99;
#7f7f7f99 는 무슨색상인가요?

2022-06-25 17:15 UTC, ypyp66 commented on src/components/lounge/NameBoard.tsx
> +  margin: -18px 0 0 0;
margin-top 속성 사용이 더 적절해보입니다

2022-06-25 17:15 UTC, ypyp66 commented on src/components/lounge/LoungeDoor.tsx
> +  padding: 7% 0 0 0;
픽셀로 가는게 좋을거같아요

2022-06-25 17:15 UTC, ypyp66 commented on src/components/lounge/LoungeDoor.tsx
> +  box-sizing: border-box;
모든 태그에 대해서 기본적으로 border-box가 적용되어있습니다

2022-06-25 17:15 UTC, ypyp66 commented on src/pages/lounge/index.tsx
> +  font-family: BlinkMacSystemFont;
여기만 폰트가 다른건가요?

2022-06-25 17:34 UTC, JJongsKim commented on src/pages/lounge/index.tsx
> +  font-family: BlinkMacSystemFont;
넹 층수 표시만 폰트가 달라서 따로 설정했습니다

2022-06-25 17:36 UTC, JJongsKim commented on src/components/lounge/NameBoard.tsx
> +  box-shadow: 0 7px 5px #7f7f7f99;
7f7f7f 로 라운지 문 그림자를 넣었는데 생각보다 진해서 비슷하게 맞추려고 알파값을 넣어봤습니다..!

2022-06-25 21:55 UTC, ndaemy commented on src/pages/lounge/index.tsx
> +  font-family: BlinkMacSystemFont;
BlinkMacSystemFont는 맥에서만 읽을 수 있는 보통은 backup용으로 사용되는 폰트입니다. 정말 폰트를 다르게 하고 싶은거라면 다른 폰트를 사용해야 할 것 같아요.

2022-06-25 22:06 UTC, ndaemy requested changes

2022-06-25 22:06 UTC, ndaemy commented on src/components/lounge/FloorButton.tsx
> +      </EachBtnWrap>
여기 네이밍이 조금 바뀌면 좋을 것 같아요. 일단 반복되는 컴퍼넌트에 Each prefix 를 붙이는건 잘 사용되지 않기도 하고, 안써있더라도 컴퍼넌트 자체가 "각각" 화면에 출력하는 애들이니까 의미가 없을거같구요.
단순히 빨리 생각나는 네이밍은 버튼들을 감싸는 컴퍼넌트는 <Buttons /> 로, 각각의 버튼들은 <Button />으로 가면 어떨까 싶은데, 요건 고민해보시고 나은 네이밍으로 바꿔보시죠!

2022-06-25 22:06 UTC, ndaemy commented on src/components/lounge/FloorData.tsx
> +export default FloorNumber;
이친구는 jsx 문법을 사용하고 있지 않으니까 .ts 확장자로도 충분할 것 같습니다.

그리고 이 데이터는 추후 서버에서 받아올 데이터니까, 파일 이름에 Demo 같은 이름을 같이 넣으면 추후에 파일 삭제할 때 좀 더 명확히 구분지을 수 있을 것 같아요

2022-06-25 22:06 UTC, ndaemy commented on src/components/lounge/LoungeDoor.tsx
> +];
요것도 데모 파일로 별도로 빼보는것도 괜찮을거같네요!

2022-06-25 22:06 UTC, ndaemy commented on src/pages/lounge/index.tsx
> +  margin-bottom: -10px;
혹시 이건 `margin-top: 10px;` 로 주면 안되는 부분일까요?

2022-06-26 15:12 UTC, JJongsKim commented on src/pages/lounge/index.tsx
> +  font-family: BlinkMacSystemFont;
넵 알겠습니다

2022-06-26 15:16 UTC, JJongsKim commented on src/components/lounge/FloorButton.tsx
> +  transform: ${props => props.downBtn && 'rotate(180deg)'};
넵 참고해서 수정해볼게요!

2022-06-26 15:17 UTC, JJongsKim commented on src/pages/lounge/index.tsx
> +  margin-bottom: -10px;
margin-top 속성으로 주면 라운지페이지 받침대랑 1층 사이에 간격이 생기더라구요!

2022-06-26 16:29 UTC, syeon2565 commented on src/components/lounge/LoungeDemoData.ts
> +};
typescript에서 타입을 명시해주는 방법은 type과 interface가 있습니다.
type과 interface 둘 다 타입을 주는건 똑같으나, interface는 확장이 가능한걸로 알고 있습니다.
저희 liontown에서 사용하는 것을 통일하면 어떨까요?

@ypyp66 혹시 둘 중 어떤걸로 통일감을 주는게 좋을까요?

2022-06-26 16:39 UTC, syeon2565 commented on src/components/lounge/LoungeDoor.tsx
> +  color: ${({ theme }) => theme.colors.text};
보니까 글씨 색상을 지정해준 것 같은데, 
이후에 global css를 수정하면서 글씨 색상을 따로 안써주셔도 됩니다.

develop 브랜치 merge이후엔 글자 색이 기본으로 적용이 되어있을테니, 지워주셔도 좋을 것 같습니다.
글자 색이 메인 글자 색이 아닌 경우에 color를 주면 됩니다.

2022-06-26 16:39 UTC, syeon2565 commented on src/pages/lounge/index.tsx
> +  position: relative;
position을 두 번 작성했습니다! 한 줄 지워주세요!

2022-06-27 00:54 UTC, ypyp66 commented on src/components/lounge/LoungeDemoData.ts
> +};
전 type이용

2022-06-27 01:46 UTC, syeon2565 commented on src/components/lounge/LoungeDemoData.ts
> +};
넵 그럼 type으로 가겠습니다 ~

2022-06-29 09:31 UTC, JJongsKim commented on src/pages/lounge/index.tsx
> +  position: relative;
넵 알겠습니다!

2022-06-29 10:04 UTC, ypyp66 approved these changes

2022-06-29 10:04 UTC, ypyp66 commented
ui 이제 그만..

2022-06-29 10:05 UTC, ypyp66 approved these changes

2022-06-29 10:05 UTC, JJongsKim commented
> ui 이제 그만..

마지막으로 하나만 보내고 머지하겠습니당

2022-06-29 10:49 UTC, ndaemy commented on src/components/lounge/LoungeDoor.tsx
> +  @media screen and (max-height: 900px) {
screen and 는 굳이 안써줘도 돼요~
그냥 `@media (max-height: ~~)` 하셔도 무방합니다

2022-06-29 10:49 UTC, ndaemy approved these changes

2022-06-29 10:53 UTC, merged