라운지 선택 컴포넌트 UI
mju-likelion/lionqueen pull request #56
Opened 2022-06-19 14:08 UTC by qkrthdus605

라운지 선택 및 라운지 생성 모달 컴포넌트

2022-06-24 16:04 UTC, syeon2565 commented on src/pages/lounge-select/index.tsx
> +import { theme } from '../../styles/theme';
theme를 import 안해줘도 사용가능하지않나요? 2

2022-06-24 16:04 UTC, syeon2565 commented on src/pages/lounge-select/Button.tsx
> +import { theme } from '../../styles/theme';
theme를 import 안해줘도 사용가능하지않나요?

2022-06-25 04:06 UTC, qkrthdus605 commented on src/pages/lounge-select/index.tsx
> +import { theme } from '../../styles/theme';
넵 해보니까 import 없이 사용가능해서 수정하도록 하겠습니다.

2022-06-25 04:06 UTC, qkrthdus605 commented on src/pages/lounge-select/Button.tsx
> +import { theme } from '../../styles/theme';
넵 해보니까 import 없이 사용가능해서 수정하도록 하겠습니다.

2022-06-25 06:13 UTC, syeon2565 reviewed
물방울버튼은 페이지가 아닌 것으로 보입니다.

컴포넌트이면, components폴더로 옮겨주세요.
pages폴더 내에 쓰면 url따라가면 해당 컴포넌트가 뜨므로 주의해주세요.

2022-06-25 22:12 UTC, ndaemy requested changes

2022-06-25 22:12 UTC, ndaemy commented on src/pages/lounge-select/Button.tsx
> +import Right from '../../../public/image/rightarrow.svg';
[이 리뷰](https://github.com/mju-likelion/lionqueen/pull/29#discussion_r906652145)를 참고해보시면 좋을 것 같습니다.

2022-06-25 22:12 UTC, ndaemy commented on src/pages/lounge-select/Button.tsx
> +// 물방울 버튼
pages 폴더 아래에는 페이지 컴퍼넌트들만 있어야 합니다. 이런 일반 컴퍼넌트가 있게 되면, 이 컴퍼넌트도 페이지 컴퍼넌트로 만들어져 버려요.

이 친구를 기준으로 설명하자면 /lounge-select/Button 이라는 페이지도 만들어진다는 얘기입니다. 이 컴퍼넌트는 components 폴더로 이동시켜야겠네요.

2022-06-25 22:12 UTC, ndaemy commented on src/pages/lounge-select/index.tsx
> +import BackgroundMain from '../../DesignSystem/BackgroundMain';
이건 `~/DesignSystem/...` 이라는 alias 가 `tsconfig.json` 에 선언되어 있어요. 이해가 안가신다면 [이 질문](https://stackoverflow.com/questions/43281741/how-to-use-paths-in-tsconfig-json)을 읽어보시면 도움이 될 것 같습니다.

2022-06-25 22:12 UTC, ndaemy commented on src/pages/lounge-select/Button.tsx
> +      </BubbleWrapper>
이 부분은 어차피 추후에 server에서 데이터를 받아오면 .map 으로 변경될테니, 지금 데모 데이터로 length 3짜리 array를 만들고 map 하면 어떨까 합니다!

2022-06-27 04:16 UTC, qkrthdus605 commented on src/pages/lounge-select/Button.tsx
> +// 물방울 버튼
넵 피드백 반영하도록 하겠습니다.

2022-06-27 04:16 UTC, qkrthdus605 commented on src/pages/lounge-select/Button.tsx
> +import Right from '../../../public/image/rightarrow.svg';
감사합니다

2022-06-27 04:17 UTC, qkrthdus605 commented on src/pages/lounge-select/Button.tsx
> +      </BubbleWrapper>
넵 그렇게 해보겠습니다!

2022-06-27 04:17 UTC, qkrthdus605 commented on src/pages/lounge-select/index.tsx
> +import BackgroundMain from '../../DesignSystem/BackgroundMain';
참고해보겠습니다.

2022-06-27 07:52 UTC, ypyp66 reviewed
svg 파일들은 icons 하위에 두는게 좋을거같아요

2022-06-27 07:53 UTC, ypyp66 commented on src/components/Button.tsx
> +    <BubbleWrapper>
key props 추가해주세요

2022-06-28 15:01 UTC, qkrthdus605 commented on src/components/Button.tsx
> +    <BubbleWrapper>
추가했습니다

2022-06-28 15:04 UTC, ypyp66 commented on src/components/BubbleButton.tsx
> +  ));
key props를 어디에 두어야하는지 검색해보는게 좋겠어요

2022-06-28 15:11 UTC, ypyp66 reviewed
아이콘 이름 변경 해주세요

2022-06-28 15:11 UTC, ypyp66 commented on src/components/icons/RightArrow.tsx
> +const XIcon = ({ width = '46', height = '52', color = '#FFF0AF' }: Props) => {
이름 변경 바랍니다

2022-06-28 15:11 UTC, ypyp66 commented on src/components/icons/Plus.tsx
> +const XIcon = ({ width = '58', height = '57', color = '#FFF0AF' }: Props) => {
이름 변경 바랍니다

2022-06-28 15:11 UTC, ypyp66 commented on src/components/icons/ModalPlus.tsx
> +const XIcon = ({ width = '38', height = '38', color = '#FFF0AF' }: Props) => {
이름변경바람

2022-06-28 15:11 UTC, ypyp66 commented on src/components/icons/Minus.tsx
> +const XIcon = ({ width = '38', height = '38', color = '#FFF0AF' }: Props) => {
이름변경요망

2022-06-28 15:12 UTC, qkrthdus605 commented on src/components/icons/Minus.tsx
> +const XIcon = ({ width = '38', height = '38', color = '#FFF0AF' }: Props) => {
헉 넵

2022-06-28 15:19 UTC, ypyp66 commented on src/components/Button.tsx
> +const Button = () => {
무슨버튼인가요?
파일명도 기능에 맞게 수정해주세요

2022-06-29 00:04 UTC, qkrthdus605 commented on src/components/Button.tsx
> +const Button = () => {
이거 변경해놨는데 아직 커밋을 안한거라 곧 올리겠습니다

2022-06-30 05:53 UTC, syeon2565 commented on src/components/LoungeSelect/BubbleMoveButton.tsx
> +  ]);
데모데이터는 파일 따로 분리해보시는 것을 추천드려요!

2022-06-30 05:53 UTC, syeon2565 commented on src/pages/lounge-select/index.tsx
> +import BackgroundMain from '../../DesignSystem/BackgroundMain';
이거... 아직 alias로 수정이 안된 것 같습니당

2022-07-01 00:54 UTC, qkrthdus605 commented on src/pages/lounge-select/index.tsx
> +import BackgroundMain from '../../DesignSystem/BackgroundMain';
수정하겠습니다

2022-07-01 00:55 UTC, qkrthdus605 commented on src/components/LoungeSelect/BubbleMoveButton.tsx
> +  ]);
넵 !

2022-07-04 06:13 UTC, syeon2565 commented on src/components/LoungeSelect/PlusModal.tsx
> +        </InputContainer>
DS에 **InputGroup**이 있는데 일부로 안쓰신건가요?
label, error가 디자인되어있습니다.

2022-07-04 14:51 UTC, qkrthdus605 commented on src/components/LoungeSelect/PlusModal.tsx
> +        </InputContainer>
엇 넵 썼다가 피그마랑 디자인이 좀 달라보여서 새로 만들어서 변경했습니다

2022-07-12 18:11 UTC, ndaemy commented on src/components/LoungeSelect/Counter.tsx
> +  };
이럴 때는 혹시 모를 상황을 위해서 방어적 프로그래밍을 하는게 좋아요

incNum 함수를 예시로 들자면
```
const incNum = () => {
  if (count >= 100) {
    setCount(100);
  else {
    ...
  }
};
```

이런 식으로?

2022-07-12 18:11 UTC, ndaemy commented on src/components/LoungeSelect/GroupList.ts
> +type GroupList = { id: number; name: string };
이 타입 사용되고 있는 곳이 없는 것 같은데 맞나요?

2022-07-13 07:35 UTC, qkrthdus605 commented on src/components/LoungeSelect/Counter.tsx
> +  };
넵 수정하겠습니다

2022-07-14 15:46 UTC, Bhanjo reviewed
리뷰가 조금 많지만 하실 수 있겠죠?ㅎㅎ
그리고 충돌 해결 부탁합니다!

2022-07-14 15:46 UTC, Bhanjo commented on src/components/LoungeSelect/PlusModal.tsx
> +      <Button onClick={onClose}>생성</Button>
이거는 나중에 헷갈리지 않도록 onClose 말고 따로 생성 함수를 만들었으면 좋겠어요

2022-07-14 15:46 UTC, Bhanjo commented on src/components/LoungeSelect/PlusModal.tsx
> +  margin-top: 35px;
이거는 margin 35 auto 0 auto로 가능하지 않나요?

2022-07-14 15:46 UTC, Bhanjo commented on src/components/LoungeSelect/PlusModal.tsx
> +        {errorShow && <CautionText>한글, 영문, 숫자 포함 12자 이내로 작성해주세요.</CautionText>}
input에 대한 디자인 시스템이 존재하는데 따로 만든 이유가 있나요??
또한, label이 아닌 p태그를 이용한 이유가 뭔가요?

2022-07-14 15:46 UTC, Bhanjo commented on src/components/LoungeSelect/PlusModal.tsx
> +  margin-bottom: 35px;
이것도 margin 하나에 축약 속성으로 표현 가능합니다!

2022-07-14 15:46 UTC, Bhanjo commented on src/components/icons/Bubble.tsx
> +const Bubble = ({ width = '163', height = '163', color = '#C5E5FF' }: Props) => {
color의 hex코드는 lint에 맞게 소문자로 바꿔주세요 다른 svg 파일도 부탁합니다!

2022-07-19 11:43 UTC, qkrthdus605 commented on src/components/LoungeSelect/BubbleMoveButton.tsx
> +  flex-direction: row;
수정했습니다.

2022-07-19 11:43 UTC, qkrthdus605 commented on src/components/LoungeSelect/Counter.tsx
> +  flex-direction: row;
수정했습니다.

2022-07-19 11:44 UTC, qkrthdus605 commented on src/components/icons/Bubble.tsx
> +const Bubble = ({ width = '163', height = '163', color = '#C5E5FF' }: Props) => {
수정했습니다.

2022-07-19 11:45 UTC, qkrthdus605 commented on src/components/LoungeSelect/PlusModal.tsx
> +      <Button onClick={onClose}>생성</Button>
저 당시에 api 문서가 생성되지 않아서 임시로 저렇게 처리했습니다.
api연동하면서 생성하도록 하겠습니다!

2022-07-19 11:48 UTC, qkrthdus605 commented on src/components/LoungeSelect/PlusModal.tsx
> +  margin-top: 35px;
수정했습니다.

2022-07-19 11:49 UTC, qkrthdus605 commented on src/components/LoungeSelect/PlusModal.tsx
> +  margin-bottom: 35px;
수정했습니다.

2022-07-19 11:54 UTC, qkrthdus605 commented on src/components/LoungeSelect/PlusModal.tsx
> +        {errorShow && <CautionText>한글, 영문, 숫자 포함 12자 이내로 작성해주세요.</CautionText>}
label에서의 for 속성을 사용해야 할 필요성을 잘 모르겠어서 단순히 p태그를 사용했습니다..!

2022-07-19 11:55 UTC, qkrthdus605 commented on src/components/LoungeSelect/Counter.tsx
> +      </ButtonWrapper>
수정했습니다.

2022-07-19 11:59 UTC, qkrthdus605 commented on src/components/LoungeSelect/BubbleMoveButton.tsx
> +  ));
div 줄여보고 배열이랑 변수명도 바꿔보겠습니다..!

2022-07-19 12:16 UTC, qkrthdus605 commented on src/components/LoungeSelect/BubbleMoveButton.tsx
> +import group from './GroupList';
`~/components/icons/Bubble` 
이렇게 해야 적용이 되는데 이미 components 폴더 안에 있는 컴포넌트인데 alias를 사용하려고 components 경로를 한 번 더 쓰는게 맞나요?

2022-07-19 14:13 UTC, qkrthdus605 commented on src/components/LoungeSelect/PlusModal.tsx
> +        </InputContainer>
넵 참고하겠습니다

2022-07-19 14:27 UTC, Bhanjo commented on src/components/LoungeSelect/BubbleMoveButton.tsx
> +import group from './GroupList';
음.. `~components/icons/`랑 `../icons/` 중에서 어떤걸 써야할지는 다른 분에게 말씀드려봐야할 듯 싶어요
저의 경우에는 통일을 하는 편인데 지금 같은 경우엔 확신이 안서네요ㄷㄷ

2022-07-19 14:35 UTC, Bhanjo commented on src/components/LoungeSelect/PlusModal.tsx
> +        {errorShow && <CautionText>한글, 영문, 숫자 포함 12자 이내로 작성해주세요.</CautionText>}
일반적으로 label의 for를 사용하는 이유는 해당 label 텍스트 클릭으로 input에 focus가 되도록 할 수 있기 때문에 쓰기도 해요

이걸 의미를 부여하자면 운동 장애가 있는 사람이 쉽게 해당 input에 포커스 혹은 체크를 할 수 있게 합니다!
또한, 시각 장애인 분들이 사용하는 스크린 리더의 접근성을 향상시켜줘요

[W3C문서](https://www.w3.org/TR/WCAG20-TECHS/H44.html#H44-description)
[스택오버플로우](https://stackoverflow.com/questions/7636502/why-use-label)

2022-07-19 15:39 UTC, qkrthdus605 commented on src/components/LoungeSelect/PlusModal.tsx
> +        {errorShow && <CautionText>한글, 영문, 숫자 포함 12자 이내로 작성해주세요.</CautionText>}
참고해보도록 하겠습니다 !

2022-07-19 15:39 UTC, qkrthdus605 commented on src/components/LoungeSelect/BubbleMoveButton.tsx
> +import group from './GroupList';
엌 넵..!

2022-07-19 15:46 UTC, Bhanjo reviewed
~~제가 올린 스레드를 참고해서 폴더 구조 변경 부탁드려요~~

제가 잘못 알려드렸어요 컴포넌트 구조 그대로 두셔도 됩니다!

2022-07-19 15:46 UTC, Bhanjo commented on src/components/LoungeSelect/BubbleMoveButton.tsx
> +  display: block;
flex와 block 중 하나만 써주세요

2022-07-19 15:48 UTC, Bhanjo commented on src/components/icons/Plus.tsx
> +const Plus = ({ width = '58', height = '57', color = '#FFF0AF' }: Props) => {
color 문자열 lint에 맞춰 주세요

2022-07-19 16:05 UTC, qkrthdus605 commented on src/components/LoungeSelect/BubbleMoveButton.tsx
> +  display: block;
옙..

2022-07-22 09:44 UTC, Bhanjo commented on src/components/LoungeSelect/BubbleMoveButton.tsx
> +  }, [currentLounge]);
마지막 페이지에서 다음 버튼을 두 번 눌러야 첫 페이지로 돌아가집니다 해결 부탁드려요!

2022-07-22 09:44 UTC, Bhanjo commented on src/pages/lounge-select/index.tsx
> +      {isModalShow && <PlusModal onClose={onClose} />}
모달 외부 클릭으로도 닫히는 기능 적용 부탁드려요

2022-07-22 10:55 UTC, syeon2565 commented on src/components/LoungeSelect/BubbleMoveButton.tsx
> +import Right from '~/components/icons/RightArrow';
alias ~components 아닌가요?

2022-07-22 10:55 UTC, syeon2565 commented on src/components/LoungeSelect/ModalForm.tsx
> +export default MyInfoModal;
이 파일 만드신 이유가 무엇이죠? 
이미 컴포넌트 폴더에 만들어져있는거면 코드 복붙으로 가져오지마시고, 재사용하면 되지 않을까요?

2022-07-22 12:16 UTC, ypyp66 commented on yarn.lock
> +
왓이즈디스?

2022-07-22 12:19 UTC, qkrthdus605 commented on yarn.lock
> +
지난 번에 디벨롭 브랜치 머지할 때 병합충돌 났을 때 incoming change로 받은 변경사항입니당 
제가 설치한 건 아니라서 잘 모르겠습니다........

2022-07-22 16:35 UTC, ypyp66 commented on yarn.lock
> +
디벨롭엔 없는데여

2022-07-22 16:52 UTC, syeon2565 commented on yarn.lock
> +
yarn.lock 파일 지우고 yarn install 다시 하고 머지해보세요.

2022-07-23 08:24 UTC, ypyp66 approved these changes

2022-07-23 09:03 UTC, ndaemy requested changes

2022-07-23 09:03 UTC, ndaemy commented on src/components/LoungeSelect/ModalForm.tsx
> +/* eslint-disable @typescript-eslint/no-empty-function */
이건 특정 줄에만 적용시키는게 안전할거같아요

2022-07-23 09:03 UTC, ndaemy commented on src/components/LoungeSelect/ModalForm.tsx
> +/* eslint-disable @typescript-eslint/no-empty-function */
아니면 lodash 의 noop 을 쓰던가?

2022-07-23 09:03 UTC, ndaemy commented on src/components/LoungeSelect/PlusModal.tsx
> +  const onChangeInput = (e: { target: { value: string } }) => {
이거 말고 React에서 지원해주는 타입을 넣어주세요
`const onChangeInput: ??? = e => { ... }` 이런식으로!

2022-07-23 13:00 UTC, ndaemy approved these changes

2022-07-23 13:00 UTC, merged