로그인 UI
mju-likelion/lionqueen pull request #59
Opened 2022-06-21 12:35 UTC by Low-ProFiles

로그인 컴포넌트 스타일만 적용하였습니다

2022-06-22 07:49 UTC, Bhanjo commented on src/pages/signin/index.tsx
> +`;
연빈이형이랑 이야기 했을 때 스타일을 맨 아래에서 작성하는 것이 가독성이 더 좋다 해서 저도 그렇게 하는 중인데
아래에 작성해보는가 어떤가요?

2022-06-22 07:51 UTC, Low-ProFiles commented
로그인 했을 때 에러메시지가 뜨는 걸 구현했습니다!

아직 계정 관련 서버가 없어서 임의로 
아이디는 lionid, 비밀번호는 lionpassword입니다.

해당 아이디 및 비밀번호로 로그인 할 시 (onSubmit처리해놨어용) 콘솔에 로그인 성공!이 뜨고
외의 아이디 및 비밀번호로 할 시 에러메시지와 함께 콘솔에 실패.. 가 뜬답니다
만약 실패해서 에러메시지가 떠 있는 상태에서 성공하신다면 에러메시지가 지워지고요!

밑에 텍스트에서 페이지 이동 구현은 다른 단계에 맞춰서 집어넣겠습니당

2022-06-22 07:51 UTC, Low-ProFiles commented on src/pages/signin/index.tsx
> +`;
바로 수정하겠슴다

2022-06-22 13:24 UTC, syeon2565 commented on src/pages/signin/index.tsx
> +                style={{ marginLeft: '12px' }}
인라인 스타일말고 다른 방법은 없을까요? 
인라인으로는 최대한 안쓰는게 좋은걸로 알고있습니다!

2022-06-22 15:48 UTC, syeon2565 commented on src/pages/signin/index.tsx
> +`;
아래에 수정한거 확인했지만, export default 보다 아래말고, 바로 위에 작성입니다!
[ 아프로디테 참고](https://github.com/mju-likelion/aphrodite/blob/develop/src/pages/applylists/ApplyLists.tsx)
작업중인 다른 ui화면도 수정하면 좋을 것 같아요.

2022-06-26 06:17 UTC, ndaemy requested changes

2022-06-26 06:17 UTC, ndaemy commented on src/pages/signin/index.tsx
> +import Button from '../../DesignSystem/Button';
얘도 ~ alias 사용해주세요

2022-06-26 06:17 UTC, ndaemy commented on src/pages/signin/index.tsx
> +    }
이 부분은 서버 응답을 mockup 한거잖아요? 그럴 거면 onSubmit 함수 안에 이 로직을 만드는 것 보단 서버 응답을 내려주는 것 같은 새로운 함수를 짜두는게 나중에 목업 함수를 빼고 실제 함수로 만드는 데 용이합니다. 함수 네이밍을 통해 mockup 이라는 걸 명확히 보여줄 수도 있구요.

2022-06-26 06:17 UTC, ndaemy commented on src/pages/signin/index.tsx
> +          <InputDiv>
다른 분들은 특정 컴퍼넌트를 감싸는 컴퍼넌트에 Wrapper suffix를 썼던데, 이 부분은 프로젝트 단위에서 통일을 해주시는게 프로젝트 가독성에 좋을 것 같아요.

2022-06-26 06:17 UTC, ndaemy commented on src/pages/signin/index.tsx
> +                onChange={e => setUserId(e.target.value)}
onChange를 props 안에서 함수를 만드는 것보단 별도의 함수로 빼는 것이 유지보수성에 좋을 것 같습니다.

2022-06-26 06:17 UTC, ndaemy commented on src/pages/signin/index.tsx
> +  display: flex;
여기선 OverLap 을 모든 styled-component 를 상속받게 만들었는데, 꼭 그래야 할 필요가 있었는지 의문이에요 (밑의 성연님 코드리뷰랑 같은 맥락에서요)

2022-07-04 07:03 UTC, syeon2565 commented on src/pages/sign-in/index.tsx
> +          <Button type="submit" style={{ width: '115px', height: '107px' }}>
인라인 스타일은 지양해주세요.

2022-07-12 18:17 UTC, ndaemy requested changes

2022-07-12 18:17 UTC, ndaemy commented on src/pages/sign-in/index.tsx
> +      <MainText> Lion Town</MainText>
맨 앞에 불필요한 white space가 있습니다
삭제해주시는게 좋을거같아요

2022-07-12 18:17 UTC, ndaemy commented on src/pages/sign-in/index.tsx
> +            </InputGroup>
이 부분 id props에 대해 https://github.com/mju-likelion/lionqueen/pull/92 에서 수정사항이 있습니다. 참고해서 git merge 받으시고 코드 수정해주셔야 정상적으로 작동할거에요.

2022-07-12 18:17 UTC, ndaemy commented on src/pages/sign-in/index.tsx
> +export default SignIn;
컴퍼넌트 선언과 export default 사이에 빈 줄을 넣어주세요

2022-07-14 15:12 UTC, Bhanjo commented on src/pages/sign-in/index.tsx
> +import React, { useState } from 'react';
`React`는 생략해도 괜찮지 않나요??

2022-07-20 06:55 UTC, Bhanjo commented on src/pages/sign-in/index.tsx
> +          <Button id="loginButton" type="submit">
저희 슬랙에서 id,class를 이용한 스타일링은 안쓰기로 한 것 같은데 확인 부탁드려요

2022-07-20 15:29 UTC, syeon2565 commented on src/pages/sign-in/index.tsx
> +  }
div:first-child의 방법 말고 다른것은 없을까요?

2022-07-20 15:29 UTC, syeon2565 commented on src/pages/sign-in/index.tsx
> +`;
이 부분은 MatinText에서 margin-bottom 주고 border주면 어떨까요?

2022-07-20 15:29 UTC, syeon2565 commented on src/pages/sign-in/index.tsx
> +  };
formik을 이용하는 것도 추천드립니다.

2022-07-23 09:04 UTC, Bhanjo commented on src/pages/sign-in/index.tsx
> +
export deafult와 컴포넌트 사이에 styled components 코드 넣어주세요

2022-07-23 13:16 UTC, syeon2565 commented on src/pages/sign-in/index.tsx
> +        console.log(err);
개발 끝날 때 콘솔 지워주세요.

2022-07-23 13:16 UTC, syeon2565 commented on src/pages/sign-in/index.tsx
> +    });
Router.push('/주소')와 동일한 코드로 수정하는 것도 좋을 것 같습니다.

2022-07-23 13:16 UTC, syeon2565 commented on src/pages/sign-in/index.tsx
> +    font-weight: 300;
혹시 글씨의 두께가 변했을까요? 변화가 없는 것 같습니다.
bold체를 원하신거라면 볼드체로 해주세요.

2022-07-23 14:20 UTC, ndaemy approved these changes

2022-07-23 14:25 UTC, merged