마이페이지 모달창 UI
mju-likelion/lionqueen pull request #72
Opened 2022-06-25 08:21 UTC by yuraup

마이페이지 - 나의 정보 모달
                             ----- 라운지 탈퇴 이중 모달
                             ----- 계정 삭제 이중 모달

2022-06-25 08:22 UTC, yuraup commented
![image](https://user-images.githubusercontent.com/81766889/175765102-fd151f5f-4659-4b85-9e11-db35a8841359.png)

확인 버튼 지우기 전입니다..! 곧 지우겠습니다

2022-06-25 12:27 UTC, syeon2565 commented on src/pages/MyPage/index.tsx
> +          <Link href="/MyPage/MyInfo">
현재 마이페이지도 그렇고, 링크 이동도 그렇고 변경이 되어야 할 것 같습니다.

pages 내의 파일 이름은 url이 됩니다.
pages내의 폴더 이름은 url naming convention을 따라주세요.
안의 컴포넌트 이름은 Pascal Case로 해주세요.

2022-06-25 12:27 UTC, syeon2565 commented on src/pages/MyPage/index.tsx
> +                  </LoungeRow>
이번껏도 LoungeRow를 크게 묶어서 스타일을 지정하기엔 어려울까요 ? 
`  <LoungeRow info="명지대..." outButton="...">` 

또한, 속한 라운지가 100개라면 100개를 다 코딩할것이 아니므로, 
가상 데이터 만들어서 map이용해보시는 거 추천드립니다.

2022-06-25 12:27 UTC, syeon2565 commented on src/pages/MyPage/index.tsx
> +  border: 1px solid #2e2e2e;
색상테마에 있는 색상이므로 색상테마 사용하시면 좋을 것 같습니다.

2022-06-25 12:27 UTC, syeon2565 commented on src/pages/MyPage/index.tsx
> +  border: 1px solid #2e2e2e;
색상테마에 있는 색상이므로 색상테마 사용하시면 좋을 것 같습니다.

2022-06-26 06:25 UTC, ndaemy requested changes

2022-06-26 06:25 UTC, ndaemy commented on src/pages/MyPage/index.tsx
>  import Button from '../../DesignSystem/Button';
DesignSystem 도 ~ alias 사용해주세요!
`~DesignSystem` 이런 식으로요!

2022-06-26 06:25 UTC, ndaemy commented on src/pages/MyPage/index.tsx
> +const NamePrintDiv = styled.div`
다른 컴퍼넌트들에는 컴퍼넌트 이름 뒤에 해당 태그 이름이 붙지 않았었으니, 이 컴퍼넌트 이름도 NamePrint 가 되는게 나을 것 같아요.
하지만 print 는 동사라서 컴퍼넌트 이름으로 또 적절치 않아보이니.. 고민해보시고 적당한 이름으로 바꿔주시는게 좋을것 같아요!

2022-06-27 12:23 UTC, ypyp66 commented on src/pages/my-page/index.tsx
> +                    {lounge.map(lounge => (
변수명이 같아요

2022-06-27 14:42 UTC, ndaemy commented on src/pages/my-page/index.tsx
> +const NameText = styled.p`
컴퍼넌트 사이에 빈 줄 한줄을 넣는 것으로 통일되면 좋을 것 같습니다!

2022-06-27 15:43 UTC, yuraup commented on src/pages/my-page/index.tsx
> +const TitleStyle = styled.button`
헉! 넵! 감사합니다

2022-06-27 15:47 UTC, yuraup commented on src/pages/my-page/index.tsx
> +  const [secondShow, setSecondShow] = useState(false);
이중모달 때문입니다. 빠른 시일 내에 구현해서 올리겠습니다!

2022-06-27 16:37 UTC, syeon2565 commented on src/pages/my-page/index.tsx
> +          </Link>
링크 이동을 한 이유가 무엇인가요? 모달이 뜰 땐 링크이동이 필요 없습니다.

2022-06-27 17:27 UTC, syeon2565 commented on src/pages/my-page/index.tsx
> +  font-weight: 300;
font-weight을 숫자로 준 이유가 무엇인가요?
bold체이면 bold체로 지정해주세요.

2022-06-28 15:23 UTC, yuraup commented
소속 라운지 박스 안에 스크롤 구현해야 하고, input창 입력하면 저장하는 기능도 구현해야 하는데..! 
이런 기능들은 이 브랜치 말고 기능 브랜치에서 할까요?

2022-06-28 15:24 UTC, ypyp66 commented on src/pages/my-page/index.tsx
> +    if (WithdrawalModalShow === true) {
true는 비교 필요x

2022-06-28 15:25 UTC, ypyp66 commented
> 소속 라운지 박스 안에 스크롤 구현해야 하고, input창 입력하면 저장하는 기능도 구현해야 하는데..! 
> 이런 기능들은 이 브랜치 말고 기능 브랜치에서 할까요?

ui끝나고 하심될듯

2022-06-28 15:38 UTC, syeon2565 commented on src/pages/my-page/index.tsx
> +          </MyInfoModal>
컴포넌트로 뺴는 것은 어떨까요?
mvp제외 기능일지라도, 버튼을 클릭했을 때 모달이 나오는데 세개의 모달에 대한것을 같이 쓰는것보다 컴포넌트로 분리하는 것도 좋은 방법 같습니다.

2022-07-01 08:00 UTC, yuraup commented
컴포넌트를 분리했는데 내 정보 모달에서 x 버튼이 안 됩니다.. 수정해보겠습니다.. 하지만 도움 주시면 감사합니다.....
![image](https://user-images.githubusercontent.com/81766889/176851319-1f2263b3-009d-4b22-bb9c-6adb829d3fe9.png)

2022-07-01 09:38 UTC, syeon2565 commented on src/pages/my-page/MyInfoModal.tsx
> +/* eslint-disable no-alert */
모달인데 page에 있으면
/my-apge/MyInfoModal 페이지 들어가면 뜹니당 ~

2022-07-02 15:14 UTC, yuraup commented
최종UI입니다

![image](https://user-images.githubusercontent.com/81766889/177006296-422d3b5e-7ed7-48c6-b2fe-3e4bb0032ff5.png)

2022-07-02 16:26 UTC, ypyp66 approved these changes

2022-07-02 18:12 UTC, merged