회원가입 폼 로직
mju-likelion/lionqueen pull request #78
Opened 2022-06-29 06:03 UTC by syeon2565

formik과 yup이용해서 폼 핸들링하고, 검증하였습니다.

2022-07-12 18:14 UTC, ndaemy requested changes

2022-07-12 18:14 UTC, ndaemy commented on src/pages/sign-up/index.tsx
> +          />
이만큼이 꾸준히 반복되는 것 같은데, 이 부분 만큼을 재활용 가능한 코드블럭을 빼낼 수 있지 않을까 싶어요

2022-07-12 18:14 UTC, ndaemy commented on yarn.lock
> +>>>>>>> origin/develop
이부분 이거 git conflict 나서 수정하라고 넣어주는 코드인데 그냥 커밋 찍어버린 것 같아요. 이러면 코드에서 에러납니다 반드시 해결하셔야 해요

2022-07-14 08:10 UTC, syeon2565 commented on yarn.lock
> +>>>>>>> origin/develop
이거 아직 푸쉬안해서 그렇습니다!!

2022-07-19 14:58 UTC, Bhanjo reviewed
~~SignUp/FormContainer.tsx는 회원 가입에서만 쓰는건가요? 아니면 비밀번호 찾기 같은 것에서도 쓰는 건가요?
회원가입에서만 쓰는거면 page/sign-up에 있어야될 것 같습니다!~~

제가 잘못알려드렸어요 그대로 두시면 됩니다!

2022-07-22 16:57 UTC, ypyp66 reviewed
에러메시지 왼쪽정렬하는게 나을듯?

2022-07-22 16:57 UTC, ypyp66 commented on src/pages/sign-up/index.tsx
> +            }}
이..이게뭐고..

2022-07-22 16:57 UTC, ypyp66 commented on src/pages/sign-up/index.tsx
> +              !!formik.errors.code
이런건 다 변수로 빼주세요

2022-07-22 17:04 UTC, ypyp66 commented on src/components/SignUp/FormContainer.tsx
> +      </ButtonBox>
이거 버튼이 쓰이는게 있고 안쓰이는게 있던데 굳이 이렇게 또 컴포넌트를 만들어야되나?

2022-07-23 07:18 UTC, syeon2565 commented on src/components/SignUp/FormContainer.tsx
> +      </ButtonBox>
회원가입, 로그인, 비밀번호찾기가  label, input, button의 차이로 컴포넌트가 다 비슷비슷하기 때문에 만들었습니다.

2022-07-23 08:27 UTC, ypyp66 approved these changes

2022-07-23 09:35 UTC, ndaemy requested changes

2022-07-23 09:35 UTC, ndaemy commented on src/lib/validation.ts
> +  // privacyCheck: Yup.boolean().oneOf([true], '회원가입을 위해 약관에 동의해주세요.'),
이거 주석을 삭제하던 살리던 하면 되지 않을까요?

2022-07-23 09:35 UTC, ndaemy commented on src/pages/sign-up/index.tsx
> +  const formik = useFormik<InitialValues>({
함수 사이를 띄우기로 한거에요 붙이기로 한거에요? 띄우는게 라이언퀸 국룰이긴 한거같은데..?

2022-07-23 09:39 UTC, ndaemy approved these changes

2022-07-23 09:40 UTC, merged